#!/bin/sh
#PBS -W group_list=ku_00016 -A ku_00016
#PBS -m ae
#PBS -M thomas.koefoed@sund.ku.dk
#PBS -l nodes=1:ppn=40
#PBS -l walltime=36:00:00

# DESCRIPTION:
# RUNS FROM THE FASTQ DIR READING FASTQ FILES (*R1_001.UMI.fastq.gz)
# AND TRIMS THE FASTQ FILES OUTPUTTING (*R1_001.UMI_trimmed.fastq.gz)


module load tools ngs
module load parallel/20210722
module load anaconda3/2021.05 perl/5.30.2 pigz/2.3.4 jdk/15.0.1 fastqc/0.11.9 trim_galore/0.6.4

cd $PBS_O_WORKDIR

my_func() {
    trim_galore -o ./ $1
}
export -f my_func
parallel --max-procs=40 my_func ::: *UMI.fastq.gz

